typography_spectrum: 0.8824594626203179
color:
  brandStrength: 0.7576489213388413
  lightness: 0.5758673697710037
  saturation: 0.08503375318832695
  rhythmicContrast: 0.10461276886053383
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.9125926431734115
author:
  name: waza
  email: 'waza =at= kosmoverse .dot. com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4364db1f-1674-4da9-a85d-64f844b0febe.jpg
name: Kosmoverse
title: >-
  There are only three things that can not be hidden: the Moon, the Sun, the
  Truth.
