typography_spectrum: 0.525440601631999
color:
  brandStrength: 0.6323635245207697
  lightness: 0.5004454313311726
  saturation: 0.15233650361187756
  rhythmicContrast: 0.6203850747551769
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.05104532209224999
author:
  name: waza
  email: 'waza =at= kosmoverse .dot. com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4364db1f-1674-4da9-a85d-64f844b0febe.jpg
name: Kosmoverse
title: >-
  There are only three things that can not be hidden: the Moon, the Sun, the
  Truth.
